# Generated by Django 4.1.2 on 2022-10-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorìa', 'verbose_name_plural': 'Categorìas'},
        ),
    ]
