# Generated by Django 4.1.2 on 2022-10-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Productos', 'verbose_name_plural': 'Productos'},
        ),
    ]
