# Generated by Django 4.1.2 on 2022-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0003_remove_category_products'),
        ('Productos', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='Categorias.category'),
        ),
    ]
