# Generated by Django 4.1.2 on 2022-10-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0003_remove_category_products'),
        ('Productos', '0003_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='Categorias.category'),
        ),
    ]
