# Generated by Django 4.1.2 on 2022-10-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0003_remove_category_products'),
        ('Productos', '0006_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='Categorias.category'),
        ),
    ]
