# Generated by Django 4.1.2 on 2022-10-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Òrden', 'verbose_name_plural': 'Òrdenes'},
        ),
    ]
